### ISSUE TITLE
Retrofit Java version to 7

### ISSUE THREAD

**Issue by dmi3coder** [dmi3coder/behaiv-java#15]
Downgrade java version to 7 because of android support. Everything except lamdas(e.g streams, utils) should be reverted to 7th analogs.
Contact me if you need help

**Comment by AndyMacDroo** [comment]
Hey @dmi3coder - I've started picking this up here:

https://github.com/dmi3coder/behaiv-java/pull/21

Not sure if you wanted me to go through the steps of backporting lambdas. Let me know :+1:

**Comment by dmi3coder** [comment]
Hello @AndyMacDroo ! Thank you for PR! Let me check how it works with android. 
Yes, for android I think as of 28th compatibility build you can specify 1.8 source version and it'll support lambdas as well as some more features + there's the ability to use retrolambda. Though it may be convenient for other developers if we'll have complete java 7 compatibilities. But for now, it's okay to keep lambdas

**Comment by dmi3coder** [comment]
Looks great! The app started successfully, one issue is the `.stream()` method. I have two ideas for that. 
One is that we can try to use rxjava for that(basically use `Flowable.just()` following by chain of actions and then `getBlocking`
e.g 
```java
features.stream().map(Pair::getKey).collect(Collectors.toCollection(ArrayList::new))
```
becomes:
```java
Flowable.fromArray(features.toArray(new Pair[]{})).map(Pair::getKey).toList().blockingGet()
```
Option two is to use retro libraries like https://github.com/stefan-zobel/streamsupport, though I don't think that'll be good idea
Last option is to use old method of doing this, just replace them with loops :)
I think the last option is the best, for now. Let me know if you want to work on it or should I take this part.
All the other changes that you've done works perfectly.

**Comment by AndyMacDroo** [comment]
Thanks @dmi3coder. I agree, maybe the simplest solution for now is to use loops? I know that streamsupport works okay but there's still some inherent verbosity (where you have to add in `new Function` to replace lambda calls) unless you also bring in `retrolambda` - so you can use lambdas and method references:
https://github.com/luontola/retrolambda

My experience of backporting lambdas and using something like retrolambda is that it often just creates headaches for project collaborators and it's hard to justify beyond the vanity of it. Most people generally understand loops so I think it's fine to be old school sometimes 🙂 

Let me know if you want me to pick up fully refactoring the existing lambdas into loops - more than happy to 🙂

**Comment by dmi3coder** [comment]
@AndyMacDroo Yes, I think it'll be the best option to make full compatibility with java7, that way developers won't need to do any other actions with the library.
Please pick up this task fully if you can. We can merge this PR and you can create another one with new changes, or just continue in the same PR.

**Comment by AndyMacDroo** [comment]
Really like the project btw 👍 

Going to try it out in a few personal projects.

**Comment by AndyMacDroo** [comment]
@dmi3coder - sure I'll finish it tonight 👍

**Comment by AndyMacDroo** [comment]
@dmi3coder would you mind merging this? Being cheeky I have my sights set on a hacktoberfest shirt so an extra PR won't hurt 😄

**Comment by dmi3coder** [comment]
Thank you for project review :) Yes sure, just merged it.
I had this idea for over 3 years and within the past year I've finally learned ML so that I can implement this project

**Comment by AndyMacDroo** [comment]
Nice. I'm happy to continue to chip in if you want someone to bounce ideas off, or for someone to work on any bits of dev :)

I'll raise the remaining changes tonight. Thanks for merging so far 👍
